src/config/urls.py
from django.contrib import admin
from django.urls import path, include

from students.views import index

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", index, name="index"),
    path("students/", include("students.urls")),
    path("groups/", include("groups.urls")),
    path("teachers/", include("teachers.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
]

src/students/urls.py
from django.contrib import admin
from django.urls import path
from students.views import hello, get_students, create_student, update_student, delete_student, search_students

app_name = "students"

urlpatterns = [
    path("hello/", hello, name="hello"),
    path("", get_students, name="get_students"),
    path("create/", create_student, name="create_student"),
    path("update/<int:pk>/", update_student, name="update_student"),
    path("delete/<int:pk>/", delete_student, name="delete_student"),
    path("search", search_students, name="search_students"),
]

src/students/models.py
import random

from django.core.validators import MinLengthValidator
from django.db import models
import datetime
from faker import Faker

from students.validators import first_name_validator


class Student(models.Model):
    first_name = models.CharField(max_length=128, null=True, validators=[MinLengthValidator(2), first_name_validator])
    last_name = models.CharField(max_length=128, null=True, validators=[MinLengthValidator(2)])
    email = models.EmailField(max_length=128)
    birthdate = models.DateField(null=True)
    grade = models.SmallIntegerField(default=0, null=True)

    def __str__(self):
        return f"{self.first_name} {self.last_name} {self.id}"

    def age(self):
        return datetime.datetime.now().year - self.birthdate.year

    @classmethod
    def generate_instances(cls, count):
        faker = Faker()
        for _ in range(count):
            cls.objects.create(
                first_name=faker.first_name(),
                last_name=faker.last_name(),
                email=faker.email(),
                birthdate=faker.date_time_between(start_date="-30y", end_date="-18y"),
                grade=random.randint(0, 100),
            )

src/students/forms.py
from django.core.exceptions import ValidationError
from django.forms import ModelForm

from students.models import Student


class StudentForm(ModelForm):
    class Meta:
        model = Student
        fields = ("first_name", "last_name", "email")

    def clean_email(self):
        email = self.cleaned_data["email"]
        if "@yandex" in email.lower():
            raise ValidationError("Yandex domain is forbidden")
        return email

    @staticmethod
    def normalize_text(text):
        return text.strip().capitalize()

    def clean_first_name(self):
        return self.normalize_text(self.cleaned_data["first_name"])

    def clean_last_name(self):
        return self.normalize_text(self.cleaned_data["last_name"])

    def clean(self):
        cleaned_data = super().clean()
        # extend parent method,  not overwrite

        first_name = cleaned_data["first_name"]
        last_name = cleaned_data["last_name"]

        if first_name == last_name:
            raise ValidationError("First name and last name can't be equal")

        return cleaned_data

src/students/views.py
from django.db.models import Q
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
from webargs.djangoparser import use_args

from students.forms import StudentForm
from students.models import Student
from students.utils import format_records
from webargs import fields


def index(request):
    return render(request=request, template_name="index.html", context={"param": [i for i in range(100)]})


def hello(request):
    return HttpResponse("Hello World!")


def get_students(request):
    students = Student.objects.all()
    return render(
        request=request,
        template_name="students_list.html",
        context={
            "students": students,
        },
    )


def search_students(request):
    students = Student.objects.all()
    search_text = request.GET.get("search")
    search_fields = ["first_name", "last_name", "email"]
    or_filter = Q()
    for field in search_fields:
        or_filter = or_filter | Q(**{f"{field}__contains": search_text})
    students = students.filter(or_filter)

    return render(request=request, template_name="search_students.html", context={"students": students})


@csrf_exempt
def create_student(request):
    if request.method == "POST":
        form = StudentForm(request.POST)

        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse("students:get_students"))

    elif request.method == "GET":
        form = StudentForm()

    return render(request=request, template_name="students_create.html", context={"form": form})


@csrf_exempt
def update_student(request, pk):

    student = get_object_or_404(Student.objects.all(), pk=pk)

    if request.method == "POST":
        form = StudentForm(request.POST, instance=student)

        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse("students:get_students"))

    elif request.method == "GET":
        form = StudentForm(instance=student)

    return render(request=request, template_name="students_update.html", context={"form": form})


@csrf_exempt
def delete_student(request, pk):
    student = get_object_or_404(Student, pk=pk)
    student.delete()

    return HttpResponseRedirect(reverse("students:get_students"))

src/students/templates/index.html
<!doctype html>
<html lang="en" class="h-100">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.98.0">
    <title>Students</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
          crossorigin="anonymous">


    <link rel="canonical" href="https://getbootstrap.com/docs/5.2/examples/cover/">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }
    </style>


    <!-- Custom styles for this template -->
    <link href="cover.css" rel="stylesheet">
  </head>
  <body class="d-flex h-100 text-center text-white bg-dark">

<div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
  <header>
    <div>
      <h3 class="float-md-start mb-0">Students</h3>
      <nav class="nav nav-masthead justify-content-center float-md-end">
        <a class="nav-link fw-bold py-1 px-0 active" aria-current="page" href="{% url "index" %}">Home</a>
        <a class="nav-link fw-bold py-1 px-0" href="{% url "students:get_students" %}">All students</a>
        <a class="nav-link fw-bold py-1 px-0" href="{% url "students:create_student" %}">Create</a>
      </nav>
    </div>
  </header>

  <main class="px-3">
    {% block content %}
    {% load static %}
    <img src="{% static "students/banner.jpg" %}" class="img-fluid" alt="Banner students"/><br><br>

    <h1>Students Database</h1><br>

    <p class="lead">Student's DataBase allows you to manage student data in an intuitive format that ensures data integrity, security, accurate reporting and quick access to information.</p>

    <div class="card-group">
      <div class="card">
        <img src="{% static "students/our-students.jpg" %}" class="card-img-top" alt="All students">
        <div class="card-body">
          <h5 class="card-title">All students</h5>
          <p class="card-text">Here you can see information about all students.</p>
          <p class="lead"><small class="text-muted">Here you can see information about all students, make search and change informaition in the database.</small></p>
          <a href="{% url "students:get_students" %}" class="btn btn-primary">All students</a>
        </div>
      </div>
      <div class="card">
        <img src="{% static "students/create_student.jpg" %}" class="card-img-top" alt="Create student">
        <div class="card-body">
          <h5 class="card-title">Create student</h5>
          <p class="card-text">Here you can add a new student to the database.</p>
          <p class="lead"><small class="text-muted">Here you can add a new student to the database. Base information is first name, last name and email.</small></p>
          <a href="{% url "students:create_student" %}" class="btn btn-primary">Create student</a>
        </div>
      </div>
    </div>

    {% endblock %}
    <br><br>
  </main>


</div>

<script
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>


  </body>
</html>

src/students/templates/search_students.html
{% extends "index.html" %}

{% block content %}
<table class="table table-dark table-striped">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">First name</th>
      <th scope="col">Last name</th>
      <th scope="col">Email</th>
      <th scope="col">Birthdate</th>
      <th scope="col">Grade</th>
      <th scope="col">Age</th>
      <th scope="col">Edit</th>
      <th scope="col">Delete</th>
    </tr>
  </thead>
  <tbody>
    {% for student in students %}
      <tr>
        <th scope="row">{{ student.id }}</th>
        <td>{{ student.first_name }}</td>
        <td>{{ student.last_name }}</td>
        <td>{{ student.email }}</td>
        <td>{{ student.birthdate }}</td>
        <td>{{ student.grade }}</td>
        {% if student.birthdate %}
          <td>{{ student.age }}</td>
        {% else %}
          <td>Undefined age</td>
        {% endif %}
        <th scope="col"><a type="button"
                                class="btn btn-warning"
        href="{% url 'students:update_student' student.id  %}">Edit</a></th>
        <th scope="col"><a type="button"
                                class="btn btn-danger"
        href="{% url 'students:delete_student' student.id  %}">Delete</a></th>
      </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}

src/students/templates/students_create.html
{% extends "index.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div>
   <form method="POST">
       {{ form|crispy }}
       <br>
       <p><button type="submit" value="Create" class="btn btn-success">Create</button></p>
   </form>
</div>

{% endblock %}

src/students/templates/students_list.html
{% extends "index.html" %}

{% block content %}
<form class="d-inline-flex p-2" role="search" method="GET" action="{% url 'students:search_students' %}">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="search">
        <button class="btn btn-outline-success" type="submit">Search</button>
</form>
  <table class="table table-dark table-striped">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">First name</th>
      <th scope="col">Last name</th>
      <th scope="col">Email</th>
      <th scope="col">Birthdate</th>
      <th scope="col">Grade</th>
      <th scope="col">Age</th>
      <th scope="col">Edit</th>
      <th scope="col">Delete</th>
    </tr>
  </thead>
  <tbody>
    {% for student in students %}
      <tr>
        <th scope="row">{{ student.id }}</th>
        <td>{{ student.first_name }}</td>
        <td>{{ student.last_name }}</td>
        <td>{{ student.email }}</td>
        <td>{{ student.birthdate }}</td>
        <td>{{ student.grade }}</td>
        {% if student.birthdate %}
          <td>{{ student.age }}</td>
        {% else %}
          <td>Undefined age</td>
        {% endif %}
        <th scope="col"><a type="button"
                                class="btn btn-warning"
        href="{% url 'students:update_student' student.id  %}">Edit</a></th>
        <th scope="col"><a type="button"
                                class="btn btn-danger"
        href="{% url 'students:delete_student' student.id  %}">Delete</a></th>
      </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}

src/students/templates/students_update.html
{% extends "index.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div>
   <form method="POST">
       {{ form|crispy }}
       <br>
       <p><button type="submit" value="Update" class="btn btn-success">Update</button></p>
   </form>
</div>

{% endblock %}